name: default

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    strategy:
      max-parallel: 5
      matrix:
        container: [ubuntu-24.04]
    runs-on: ${{matrix.container}}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install apt-get dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake g++ python3-pip wget git libasio-dev libtinyxml2-dev libssl-dev libp11-dev softhsm2 libengine-pkcs11-openssl

      - name: Build Fast DDS dependencies
        run: |
            mkdir build && cd build 
            cmake -DBUILD_FAST_DEPENDENCIES=ON ..
            make -j install

      - name: Build Fast DDS
        run: |
            cd build
            cmake -DBUILD_FAST_DDS=ON ..
            make -j install

      - name: Build Fast DDS Sample
        run: |
            cd build
            cmake -DBUILD_FAST_DDS_SAMPLE=ON ..
            make -j